#!/usr/bin/env bash
_path=$(cd "${BASH_SOURCE[0]%/*}"; pwd)

. "$_path/../../lib/tap.sh"

cp -f "$1" $wdir/output
jqf=".[].value.content|{type,sources,price,priceHex}"
mapfile -t symbols < <(jq -r '.pairs|keys|.[]|sub("/";"")' "$_path/omnia.conf")

plan $((${#symbols[@]} * 2))

note <<<"Gofer Regression Assertions"

for symbol in "${symbols[@]}"; do
  jqfs="$jqf|select(.type == \"$symbol\")"

  assert "ssb message for $symbol isn't empty" \
    json "$jqfs != null" <<<"true"
  assert "ssb message for $symbol hasn't changed" \
    json "$jqfs" <<<$(jq "$jqfs" "$_path/ssb-messages.json")
done
