#!/usr/bin/env bash
_path=$(cd "${BASH_SOURCE[0]%/*}"; pwd)

. "$_path/../../lib/tap.sh"
plan 4

cp -f "$1" $wdir/output

cat $wdir/output | note

assert "ssb messages has all asset pairs" \
  json '[.[].value.content.type]|sort' <<<$(jq '[.pairs|keys|.[]|sub("/";"")]|sort' "$_path/omnia.conf")
assert "ssb message pair" \
  json '[.[].value.content.type|type == "string"]|all' <<<"true"
assert "ssb message version" \
  json '[.[].value.content.version|type == "string"]|all' <<<"true"
assert "ssb message price" \
  json '[.[].value.content.price|type == "number"]|all' <<<"true"
