#!/usr/bin/env bash
_path=$(cd "${BASH_SOURCE[0]%/*}"; pwd)

. "$_path/../../lib/include.sh"

export OMNIA_CONFIG="$_path/omnia.conf"
export OMNIA_GOFER_CONFIG="$_path/gofer.json"
export OMNIA_SOURCE_PARALLEL=1
export OMNIA_DEBUG=1
export OMNIA_VERBOSE=1

runOmnia
