#!/usr/bin/env bash
set -o pipefail

_path="$(cd ${BASH_SOURCE[0]%/*}; pwd)"

ecode=0

while [[ "$1" ]]; do
  case "$1" in
    --update|--record)
      export E2E_RECORD=1;;
    *)
      targets+=("$1");;
  esac
  shift
done

if [[ -z $targets ]]; then
  targets=($(cd "$_path"; find * -maxdepth 0 -type d ! -name "_*"))
fi

mkdir -p logs

for target in "${targets[@]}"; do
  export E2E_TARGET="$target"
  export E2E_TARGET_DIR="$_path/$target"

  {
    if [[ $E2E_RECORD ]]; then
      if [[ -x "$E2E_TARGET_DIR/record" ]]; then
        echo >&2 "# Record new regression for target '$target'"
        "$E2E_TARGET_DIR/record"
      else
        echo >&2 "# No $E2E_TARGET_DIR/record for target '$target', skipped"
        continue
      fi
    else
      if [[ -x "$E2E_TARGET_DIR/replay" ]]; then
        echo >&2 "# Test regression for target '$target'"
        "$E2E_TARGET_DIR/replay"
      else
        echo >&2 "# No $E2E_TARGET_DIR/replay for target '$target', skipped"
        continue
      fi
    fi
  } | tee "logs/$target.tap" || ecode=1
done

exit $ecode
