#!/usr/bin/env bash
_path=$(cd "${BASH_SOURCE[0]%/*}"; pwd)

. "$_path/../../lib/tap.sh"

mapfile -t pairs < <(jq -r '.pairs|keys|.[]|select(. != "ETH/BTC")' <"$_path/omnia.conf")

cp -f "$1" $wdir/output

plan $((${#pairs[@]} * 2))

note <<<"Relay with Spire Transport Regression Assertions"

for pair in "${pairs[@]}"; do
  assert "Oracle price for $pair not null" \
    json --arg p $pair '.[$p] != null' <<<"true"
  assert "Oracle price for $pair" \
    json --arg p $pair '.[$p]' <<<$(jq --arg p $pair '.[$p]' "$_path/good.json")
done
