#!/usr/bin/env bash
set -xe

SCRIPT_DIR=$(cd "${BASH_SOURCE[0]%/*}" && pwd)
TARGET_DIR=${TARGET_DIR:-/etc/systemd/system}
OMNIA_PATH=${OMNIA_PATH:-omnia}
SSB_PATH=${SSB_PATH:-ssb-server}

subst() {
  # shellcheck disable=SC2016
  envsubst '$USER $OMNIA_PATH $SSB_PATH' < "$1" > "$TARGET_DIR"/"${1##*/}"
}

for service in "$SCRIPT_DIR"/*.service; do
  subst "$service"
done
