#!/usr/bin/env bash
_path=$(cd "${BASH_SOURCE[0]%/*}"; pwd)

. "$_path/../../lib/tap.sh"
plan 4

cp -f "$1" $wdir/output

assert "spire messages has all asset pairs" \
  json '[.[].price.wat]|sort' <<<$(jq -r '[.pairs[]]|sort' "$_path/spire.json")
assert "ssb message pair" \
  json '[.[].price.wat|type == "string"]|all' <<<"true"
assert "ssb message version" \
  json '[.[].price.val|type == "string"]|all' <<<"true"
assert "ssb message price" \
  json '[.[].price.age|type == "number"]|all' <<<"true"
