#!/usr/bin/env bash
_path=$(cd "${BASH_SOURCE[0]%/*}"; pwd)

. "$_path/../../lib/tap.sh"

rmPairs='
["ETH/BTC"
,"AAVE/USD"
,"UNI/USD"
]'
mapfile -t pairs < <(jq -r --argjson rp "$rmPairs" '
  .pairs|keys|.[]|select([.]|inside($rp)|not)
' < "$_path/omnia.conf")


cp -f "$1" $wdir/output

plan $((${#pairs[@]} * 2))

note <<<"Relayer Regression Assertions"

for pair in "${pairs[@]}"; do
  assert "Oracle price for $pair not null" \
    json --arg p $pair '.[$p] != null' <<<"true"
  assert "Oracle price for $pair" \
    json --arg p $pair '.[$p]' <<<$(jq --arg p $pair '.[$p]' "$_path/good.json")
done
