#!/usr/bin/env bash
_path=$(cd "${BASH_SOURCE[0]%/*}"; pwd)

. "$_path/../../lib/tap.sh"
plan 3

cp -f "$1" $wdir/output

assert "has all asset pairs" \
  json 'keys|sort' <<<$(jq '[.pairs|keys|.[]|select(. != "ETH/BTC")]|sort' "$_path/omnia.conf")
assert "asset pairs not null" \
  json '[.[] != null]|all' <<<"true"
assert "asset pairs not 0" \
  json '[.[] > 0]|all' <<<"true"
